accounts/api/urls.py
from django.urls import path

from .views import AuthApiView, LogoutApiView, VerifyApiView, DeleteAccountApiView

urlpatterns = [
    path("auth/", AuthApiView.as_view()),
    path("verify/", VerifyApiView.as_view()),
    path("logout/", LogoutApiView.as_view()),
    path("delete_account/", DeleteAccountApiView.as_view()),
]

accounts/urls.py
from django.urls import include, path

from accounts.api.urls import urlpatterns

from .views import (AddNewAdminView, AdminListView, AdminLoginView, LogoutView,
                    UserDeleteView, UserDetailView, UserListView)

app_name = "accounts"

urlpatterns = [
    path("login/", AdminLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("admin_list/", AdminListView.as_view(), name="admin_list"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("admin_create/", AddNewAdminView.as_view(), name="admin_create"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="delete"),
    path("user_detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("api/", include(urlpatterns)),
]

chat/urls.py
from django.urls import include, path

from chat.api.urls import urlpatterns

app_name = "chat"
urlpatterns = [
    path("api/", include(urlpatterns)),
]

lovinoo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("config.urls", namespace="config")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("activity/", include("activity.urls", namespace="activity")),
    path("financial/", include("financial.urls", namespace="financial")),
]
if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

    

accounts/models.py
import datetime

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from .managers import MyUserManager


# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    phone_number = models.CharField(max_length=11, unique=True)
    fcm_token = models.TextField()

    USERNAME_FIELD = "phone_number"
    REQUIRED_FIELDS = []

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = MyUserManager()

    def __str__(self):
        return self.phone_number

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def get_account_expire_days(self):
        from financial.models import PayHistory, Tariff

        expire_date = None
        pay_history = PayHistory.objects.filter(user_id=self.id).first()
        if pay_history:
            tariff = Tariff.objects.filter(title=pay_history.tariff).first()
            if tariff:
                expire_date = pay_history.date + datetime.timedelta(days=tariff.time)
                today = datetime.datetime.today()
                expire_time = expire_date.date() - today.date()

                expire_date = expire_time.days

        return expire_date


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11)
    code = models.CharField(max_length=6)
    created = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.validators import ValidationError

from .models import User


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("phone_number",)

    # def clean(self):
    #     cleand_data = super(UserCreationForm, self).clean()
    #     password = cleand_data["password"]
    #     password_confirm = cleand_data["password_confirm"]
    #     if (password and password_confirm) and (password_confirm != password_confirm):
    #         raise ValidationError("unmatched password")
    #     return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text='you can change password using <a href="../password/">this form</a>.'
    )

    class Meta:
        model = User
        fields = (
            "phone_number",
            "password",
        )


class AuthForm(forms.Form):
    phone_number = forms.CharField(
        label="نام کاربری",
        widget=forms.TextInput(
            attrs={"placeholder": "نام کاربری", "class": "form-control text-left"}
        ),
    )

    password = forms.CharField(
        label="رمز عبوز",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "رمز عبور",
                "class": "form-control text-left",
            }
        ),
    )


class AdminForm(AuthForm):
    password_confirm = forms.CharField(
        label="نایید رمز عبور",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "تایید  رمز عبوز",
                "class": "form-control text-left",
            }
        ),
    )

    def clean(self):
        clean_data = super(AdminForm, self).clean()
        password, password_confirm = (
            clean_data["password"],
            clean_data["password_confirm"],
        )
        if (password and password_confirm) and (password != password_confirm):
            raise ValidationError("dis match")

accounts/api/views.py
import random

from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from rest_framework import authentication, generics, status
from rest_framework.authtoken.models import Token
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

from ..models import OtpCode
from ..utils import send_otp
from .serializers import AuthSerializer, VerifySerializer

user = get_user_model()


# class UserApiView(
#     mixins.CreateModelMixin,
#     mixins.ListModelMixin,
#     mixins.RetrieveModelMixin,
#     generics.GenericAPIView):
#     serializer_class =
#     queryset =
#     lookup_field =
#     permission_classes = [permissions.IsAuthenticated]
#     authentication_classes = [authentication.SessionAuthentication]
#
#     def get(self, request, *args, **kwargs):
#         pk = kwargs.get('pk')
#         if pk:
#             return self.retrieve(request, *args, **kwargs)
#         return self.list(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         return self.create(request, *args, **kwargs)
#
#     def perform_create(self, serializer):
#         serializer.save()


class AuthApiView(generics.GenericAPIView):
    serializer_class = AuthSerializer
    permission_classes = [
        AllowAny,
    ]

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid(raise_exception=True):
            random_code = random.randint(000000, 999999)
            phone_number = serializer.validated_data["phone_number"]
            OtpCode.objects.create(phone_number=phone_number, code=random_code)
            send_otp(phone_number=phone_number, code=random_code)
            context = {
                "is_done": True,
                "message": "پیام ارسال شد",
                "data": serializer.data,
            }
            return Response(data=context, status=status.HTTP_200_OK)
        context = {
            "is_done": False,
            "message": "خطا در پارامتر ارسالی",
            "data": serializer.errors,
        }
        return Response(data=context, status=status.HTTP_400_BAD_REQUEST)


class VerifyApiView(generics.GenericAPIView):
    serializer_class = VerifySerializer
    permission_classes = [
        AllowAny,
    ]

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid(raise_exception=True):
            phone_number = serializer.validated_data["phone_number"]
            code = serializer.validated_data["code"]
            otp_obj = OtpCode.objects.filter(phone_number=phone_number).last()
            if otp_obj and otp_obj.code == code:
                try:
                    user_obj = user.objects.get(phone_number=phone_number)
                    user_obj.fcm_token = serializer.validated_data["fcm_token"]
                    user_obj.save()
                    token, created = Token.objects.get_or_create(user=user_obj)
                    context = {
                        "is_done": True,
                        "message": "کاربر با موفقیت وارد شد",
                        "token": token.key,
                    }
                    return Response(data=context, status=status.HTTP_200_OK)
                except user.DoesNotExist:
                    user_obj = user.objects.create_user(phone_number=phone_number)
                    user_obj.fcm_token = serializer.validated_data["fcm_token"]
                    user_obj.save()
                    token_obj = Token.objects.create(user=user_obj)
                    context = {
                        "is_done": True,
                        "message": "کاربر با موفیت ساخته شد",
                        "token": token_obj.key,
                    }
                    return Response(data=context, status=status.HTTP_200_OK)
            else:
                context = {
                    "is_done": False,
                    "message": "کد ارسال برای کاربر با کد ذزیافتی همخوانی ندارد",
                }
                return Response(data=context, status=status.HTTP_400_BAD_REQUEST)
        context = {
            "is_done": False,
            "message": "خطا در پارامتر ارسالی",
        }
        return Response(data=context, status=status.HTTP_400_BAD_REQUEST)


class LogoutApiView(generics.GenericAPIView):
    @staticmethod
    def delete(request, *args, **kwargs):
        request.user.auth_token.delete()
        context = {
            "is_done": True,
            "message": "token کاربر با موفقیت حذف شد",
        }
        return Response(data=context, status=status.HTTP_200_OK)


class DeleteAccountApiView(generics.GenericAPIView):

    def get(self, request, *args, **kwargs):
        user_obj = get_object_or_404(user, id=request.user.id)
        user_obj.delete()
        return Response(data={
            "is_done": True,
            "message": "کاربر با موفقیت حذف شد",
        })

accounts/views.py
from braces.views import (AnonymousRequiredMixin, LoginRequiredMixin,
                          SuperuserRequiredMixin)
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy

from django.views.generic import DetailView, FormView, ListView, View

from .forms import AdminForm, AuthForm

user = get_user_model()


class AdminLoginView(AnonymousRequiredMixin, View):
    """
    login view for accessing panel
    """

    form_class = AuthForm
    template_name = "accounts/login.html"

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user_obj = authenticate(
                phone_number=cd["phone_number"], password=cd["password"]
            )
            if user_obj and user_obj.is_admin:
                login(request, user_obj)
                messages.success(request, "با موفقیت وارد شدید", "success")
                return redirect("config:panel")
            messages.error(request, "خطا در ورود", "danger")
        return render(request, self.template_name, {"form": form})


class AddNewAdminView(SuccessMessageMixin, FormView):
    form_class = AdminForm
    success_url = reverse_lazy("accounts:admin_list")
    template_name = "accounts/admin_create.html"
    success_message = "ادمین با موققیت اضافه شد"

    def form_valid(self, form):
        clean_data = form.cleaned_data
        user(phone_number=clean_data["phone_number"],
             password=clean_data["password"])
        user.is_admin = True
        user.save()
        return super(AddNewAdminView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "خطا در افزودن کاربر ادمین", "danger")
        return super(AddNewAdminView, self).form_invalid(form)


class UserDeleteView(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_id = kwargs.get("pk")
        user_obj = get_object_or_404(user, id=user_id)
        user_obj.delete()
        messages.success(
            request, "کاربر با موفقیت حذف شد و ابن شماره به لیست کاربران بلاک شده انتقال پیدا کرد", "success")
        return redirect(request.META.get('HTTP_REFERER'))


class AdminListView(ListView):
    def get_queryset(self):
        admin_list = user.objects.filter(is_admin=True, is_superuser=False)
        return admin_list

    template_name = "accounts/admin_list.html"


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, "", "success")
        return redirect("accounts:login")


class UserListView(ListView):
    queryset = user.objects.exclude(
        is_admin=True, is_superuser=True).select_related('profile')
    template_name = "accounts/user_list.html"


class UserDetailView(DetailView):
    queryset = user.objects.exclude(
        is_admin=True, is_superuser=True).select_related('profile')
    template_name = "accounts/user_detail.html"
    context_object_name = 'user'

accounts/templates/accounts/admin_create.html
{% extends 'base.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-success text-center">افزودن کاربر ادمین</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        {% for field in form.visible_fields %}
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        {% endfor %}
                                        <button type="submit" class="btn btn-primary">ثبت</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->

accounts/templates/accounts/admin_list.html
{% extends "base.html" %}
{% block content %}
    <main class="main-content">
        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">لیست کاربران ادمین</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">


                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">کاربران ادمین</h6>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">شماره تماس</th>
                                        <th scope="col">اخرین ورود</th>
                                        <th scope="col">تنظیمات</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for admin in admin_list %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ admin.phone_number }}</td>
                                            <td> {% if admin.last_login %}
                                                {{ admin.last_login }}
                                            {% else %}
                                                ---
                                            {% endif %}
                                            </td>
                                            <td><a class="btn btn-danger" href="{% url "accounts:delete" admin.pk %}">حذف
                                                ادمین</a></td>
                                        </tr>
                                    {% empty %}
                                        <h1 class="text-center text-danger">ادمینی در سیستم ثبت نشده</h1>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>قالب Protable - قالب پنل مدیریت</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'media/image/favicon.png' %}">

    <!-- Plugin styles -->
    <link rel="stylesheet" href="{% static 'vendors/bundle.css' %}" type="text/css">

    <!-- App styles -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css">
</head>
<body class="form-membership">

<!-- begin::preloader-->
<div class="preloader">
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="50px" height="50px" viewbox="0 0 128 128"
         xml:space="preserve">
        <rect x="0" y="0" width="100%" height="100%" fill="#FFFFFF"/>
        <g>
            <path d="M75.4 126.63a11.43 11.43 0 0 1-2.1-22.65 40.9 40.9 0 0 0 30.5-30.6 11.4 11.4 0 1 1 22.27 4.87h.02a63.77 63.77 0 0 1-47.8 48.05v-.02a11.38 11.38 0 0 1-2.93.37z"
                  fill="#000000" fill-opacity="1"/>
        </g>
    </svg>
</div>
<!-- end::preloader -->

<div class="form-wrapper">

    <!-- logo -->
    <div id="logo">
        <img class="logo" src="{% static 'media/image/logo.png' %}" alt="image">
        <img class="logo-dark" src="{% static 'media/image/logo-dark.png' %}" alt="image">
    </div>
    <!-- ./ logo -->

    <h5>ورود</h5>

    <!-- form -->
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group">
            {{ form.phone_number }}
        </div>
        <div class="form-group">
            {{ form.password }}
        </div>
        <div class="form-group text-left d-sm-flex justify-content-between mb-4">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" checked id="customCheck1">
                <label class="custom-control-label" for="customCheck1">به خاطر سپاری</label>
            </div>
            <a href="recover-password.html" class="line-height-28">بازنشانی رمز عبور</a>
        </div>
        <button  type="submit" class="btn btn-primary btn-block">ورود</button>
        <hr>
    </form>
    <!-- ./ form -->

</div>

<!-- Plugin scripts -->
<script src="{% static 'vendors/bundle.js' %}"></script>

<!-- App scripts -->
<script src="{% static  'js/app.js' %}"></script>
</body>
</html>

accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}
{% block content %}
    <!-- begin::main-content -->
    <main class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h4>کاربر {{ user }}</h4>
                <nav aria-label="breadcrumb">
                    <input
                            action="action"
                            onclick="window.history.go(-1); return false;"
                            type="submit"
                            value="بازگشت به صفحه قبل"
                            class="btn btn-danger"
                    />
                </nav>
            </div>


            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card-group">
                        <div class="card">
                            <div class="card-body">
                                <h1 class="card-title text-center">{{ user.phone_number }}</h1>
                                <ul>
                                    <li><h1>نام:{{ user.profile.first_name }}</h1></li>
                                    <li><h1>نام خانوادگی:{{ user.profile.first_name }}</h1></li>
                                    <li><h1>استان:{{ user.profile.province }}</h1></li>
                                    <li><h1>شهر:{{ user.profile.city }}</h1></li>
                                </ul>
                                <p class="card-text"><h1>bio:</h1>:<br><h3>{{user.profile.bio |linebreaksbr }}</h3></p>
                                <p class="card-text">
                                    <a href="{% url "accounts:delete"  user.pk%}" class="btn btn-danger">حذف کاربر</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <h1 class="text-center text-info">تصاویر پروفایل</h1>
                    <div class="card-columns">
                        {% for image in user.images.all %}
                            <div class="card">
                                <a href="{{ image.image.url }}">
                                    <img width="50px" height="150px" src="{{ image.image.url }}" class="card-img-top"
                                         alt="image">
                                </a>
                            </div>
                        {% empty %}
                            <h1 class="text-center">تصویری برای نمایش وجود ندارد</h1>
                        {% endfor %}


                    </div>

                </div>
            </div>

        </div>

    </main>
    <!-- end::main-content -->
{% endblock content %}

accounts/templates/accounts/user_list.html
{% extends "base.html" %}
{% block content %}
    <main class="main-content">
        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">لیست کاربران کاربران</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">


                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">کاربران </h6>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">شماره تماس</th>
                                        <th scope="col">نام و نام خانوادگی</th>
                                        <th scope="col">استان</th>
                                        <th scope="col">سن</th>
                                        <th scope="col">نمایش اطلاعات کامل</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for user in user_list %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ user.phone_number }}</td>
                                            <td>{{ user.profile.first_name }}-{{ user.profile.last_name }}</td>
                                            <td>{{ user.profile.province }}</td>
                                            <td>{{ user.profile.age }}</td>
                                            <td><a class="btn btn-danger" href="{% url "accounts:user_detail" user.pk %}">
                                               نمایش</a></td>
                                        </tr>
                                    {% empty %}
                                        <h1 class="text-center text-danger">کاربری در سیستم ثبت نشده</h1>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </main>
{% endblock content %}