chat/urls.py
from django.urls import include, path

from chat.api.urls import urlpatterns

app_name = "chat"
urlpatterns = [
    path("api/", include(urlpatterns)),
]

config/api/urls.py
from django.urls import path

from .views import (CityListApiView, ContactUsCreateAPiView,
                    RateApiView)

# from .views import (CityListApiView, ContactUsCreateAPiView,
#                     RuleApiView, PrivacyApiView, AboutUsApiView,RateApiView)

app_name = "config"
urlpatterns = [
    # path("rule/", RuleApiView.as_view()),
    path("city_list/", CityListApiView.as_view()),
    path("contact_us/", ContactUsCreateAPiView.as_view()),
    # path("privacy/", PrivacyApiView.as_view()),
    # path("aboutus/", AboutUsApiView.as_view()),
      path("rate/", RateApiView.as_view()),

]

config/urls.py
from django.urls import include, path

from config.api.urls import urlpatterns

from .views import (ContactDetailView,
                    ContactListView, PanelView, LandingView)

from .views import (AboutUsCreateView, AboutUsView, ContactDetailView,
                PanelView, RuleCreateView, RuleView, LandingView)


app_name = "config"

urlpatterns = [
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("about_create/", AboutUsCreateView.as_view(), name="about_create"),
    path("rule_create/", RuleCreateView.as_view(), name="rule_create"),
    path("rule/", RuleView.as_view(), name="rule"),
    path("contact_list/", ContactListView.as_view(), name="contact_list"),
    path(
        "contact_detail/<int:pk>/", ContactDetailView.as_view(), name="contact_detail"
    ),
    path("api/", include(urlpatterns)),
    path("panel/", PanelView.as_view(), name="panel"),
    path("", LandingView.as_view(), name="landing"),
]

lovinoo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("config.urls", namespace="config")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("activity/", include("activity.urls", namespace="activity")),
    path("financial/", include("financial.urls", namespace="financial")),
]
if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

    

config/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.core.validators import MaxValueValidator
from django.conf import settings

user = settings.AUTH_USER_MODEL
# Create your models here.


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.__class__.objects.exclude(id=self.id).delete()
        super(SingletonModel, self).save(*args, **kwargs)

    @classmethod
    def load(cls):
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls()


# class ConfigBase(SingletonModel):
#     title = models.CharField(max_length=125)
#     description = RichTextField()

#     def __str__(self):
#         return self.title


class Rules(models.Model):
    title = models.CharField(max_length=125)
    description = RichTextField()

    def __str__(self):
        return self.title



class AboutUs(models.Model):
    title = models.CharField(max_length=125)
    description = RichTextField()

    def __str__(self):
        return self.title



class Privacy(models.Model):
    title = models.CharField(max_length=125)
    description = RichTextField()

    def __str__(self):
        return self.title



class Contact(models.Model):
    title = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    

class Rate(models.Model):
    number = models.PositiveIntegerField(validators=[MaxValueValidator(5)])
    user = models.OneToOneField(user, on_delete=models.CASCADE, related_name='rate')
    

config/forms.py
from django import forms

from .models import AboutUs, Rules


class AboutUsForm(forms.ModelForm):
    class Meta:
        model = AboutUs
        fields = {
            "title",
            "description",
        }
        labels = {
            "title": "عنوان",
            "description": "توضیحات",
        }
        widgets = {"title": forms.TextInput(attrs={"class": "form-control"})}


class RuleForm(forms.ModelForm):
    class Meta:
        model = Rules
        fields = {
            "title",
            "description",
        }
        labels = {
            "title": "عنوان",
            "description": "توضیحات",
        }
        widgets = {"title": forms.TextInput(attrs={"class": "form-control"})}

config/api/views.py
from rest_framework import generics, status
from rest_framework.response import Response

from utils.city import cities

from ..models import AboutUs, Contact, Rules, Privacy,Rate
from .serializers import ContactSerializer, RateSerializer

# from .serializers import AboutUsSerializer, ContactSerializer, RulesSerializer, PrivacySerializer,RateSerializer


# class PrivacyApiView(generics.GenericAPIView):
#     serializer_class = PrivacySerializer
#     queryset = Privacy.load()

#     def get(self, request, *args, **kwargs):
#         serializer = self.serializer_class(self.queryset)
#         context = {"is_done": True, "message": "متن حریم خصوصی ", "data": serializer.data}
#         return Response(data=context, status=status.HTTP_200_OK)


# class AboutUsApiView(generics.GenericAPIView):
#     serializer_class = AboutUsSerializer
#     queryset = AboutUs.load()

#     def get(self, request, *args, **kwargs):
#         serializer = self.serializer_class(self.queryset)
#         context = {"is_done": True, "message": "متن درباره ما", "data": serializer.data}
#         return Response(data=context, status=status.HTTP_200_OK)


#
#
# class RuleApiView(generics.GenericAPIView):
#     serializer_class = RulesSerializer
#     queryset = Rules.load()

#     def get(self, request, *args, **kwargs):
#         serializer = self.serializer_class(self.queryset)
#         context = {"is_done": True, "message": "متن قوانین", "data": serializer.data}
#         return Response(data=context, status=status.HTTP_200_OK)


# class RuleApiView(ListAPIView):
#     serializer_class = RulesSerializer
#     queryset = Rules.load()
#
#     def list(self, request, *args, **kwargs):
#         response = super().list(request, *args, **kwargs)
#         return response({
#             "is_done": True
#         })
#
#
# class AboutUsApiView(ListAPIView):
#     queryset = AboutUs.load()
#     serializer_class = AboutUsSerializer
#
#     def list(self, request, *args, **kwargs):
#         response = super().list(request, *args, **kwargs)
#         return response({
#             'is_done': True
#         })


class CityListApiView(generics.GenericAPIView):
    """
    this view is for getting the city of province;
    query params as province passed in views urls and filter down base on that
    """

    def get(self, request, *args, **kwargs):
        province = self.request.query_params.get("province")
        city_list = [item for item in cities if item["state"] == province]
        context = {
            "is_done": True,
            "message": f"لیست شهرهای {province}",
            "city": city_list,
        }
        return Response(data=context, status=status.HTTP_200_OK)


class ContactUsCreateAPiView(generics.CreateAPIView):
    """
    this view is for creating contact;
    """

    queryset = Contact.objects.all()
    serializer_class = ContactSerializer

    def create(self, request, *args, **kwargs):
        response = super().create(request, *args, **kwargs)
        return Response(
            {
                "is_done": True,
                "message": "پیام با موفقیت ارسال شد",
                "data": response.data,
            }
        )
    
class RateApiView(generics.GenericAPIView):
    serializer_class = RateSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid(raise_exception=True):
            obj, created = Rate.objects.update_or_create(
                user=request.user,
                defaults={'number': serializer.validated_data['number']},
            )
            context = {
                'is_done': True,
                'message': 'rate submitted'
            }
            return Response(data=context, status=status.HTTP_200_OK)
        context = {
            'is_done': True,
            'message': serializer.errors
        }
        return Response(data=context, status=status.HTTP_400_BAD_REQUEST)    

config/views.py
from django.contrib.auth import get_user_model
from django.db.models import Sum
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, TemplateView

from activity.models import ReportedUser
from chat.models import Message, Room
from financial.models import CartPay, OriginCart, PayHistory, Tariff
from utils.mixins import AdminUserMixin

from .forms import AboutUsForm, RuleForm
from .models import Contact
from .models import AboutUs, Contact, Rules

user = get_user_model()


def home(request):
    return render(request, "index.html")


class PanelView(AdminUserMixin, View):
    def get(self, request, *args, **kwargs):
        user_count = user.objects.exclude(is_admin=True, is_superuser=True).count()
        admin_count = user.objects.filter(is_admin=True).count()
        tariff_count = Tariff.objects.count()
        origin_cart_count = OriginCart.objects.count()
        pay_count = PayHistory.objects.count()
        cart_pay_count = CartPay.objects.filter(status="waiting").count()
        reported_count = ReportedUser.objects.all().count()
        contact_count = Contact.objects.count()
        total_pay = PayHistory.objects.aggregate(total_pay=Sum("price"))["total_pay"]
        message_count = Message.objects.count()
        room_count = Room.objects.count()
        context = {
            "user_count": user_count,
            "admin_count": admin_count,
            "total_pay": total_pay,
            "tariff_count": tariff_count,
            "origin_cart_count": origin_cart_count,
            "pay_count": pay_count,
            "cart_pay_count": cart_pay_count,
            "reported_count": reported_count,
            "contact_count": contact_count,
            "message_count": message_count,
            "room_count": room_count,
        }
        return render(request, "config/home.html", context)


class AboutUsView(View):
    def get(self, request):
        about_us = AboutUs.load()
        return render(request, "config/about_us.html", {"about_us": about_us})


class RuleView(View):
    def get(self, request):
        about_us = Rules.load()
        return render(request, "config/rule.html", {"rule": about_us})


class ContactListView(ListView):
    model = Contact
    template_name = "config/contact_list.html"


class ContactDetailView(DetailView):
    model = Contact
    template_name = "config/contact_detail.html"


class AboutUsCreateView(CreateView):
    model = AboutUs
    form_class = AboutUsForm
    template_name = "config/about_create.html"
    success_url = reverse_lazy("config:about_us")


class RuleCreateView(CreateView):
    model = Rules
    form_class = RuleForm
    template_name = "config/rule_create.html"
    success_url = reverse_lazy("config:rule")


class StaticView(AdminUserMixin, View):
    def get(self, request, *args, **kwargs):
        # category = Category.objects.all()
        # want_ad = WantAd.objects.all()
        # today_want_ad = want_ad.filter(created=jdatetime.date.today())
        # not_confirmed = today_want_ad.filter(confirmed=False).count()
        # month_want_ad = want_ad.filter(created__month=jdatetime.date.today().month).count()
        # year_want_ad = want_ad.filter(created__year=jdatetime.date.today().year).count()
        # special_want = want_ad.filter(express=True).count()
        # top_city = want_ad.annotate(top_city=Count('city')).order_by('-top_city').first()
        # top_date = want_ad.annotate(top_date=Count('created')).order_by('-created').first()
        # top_zone = want_ad.annotate(top_zone=Count('zone')).order_by('-top_zone').first()
        # paid = want_ad.filter(category__paid=True).count()
        # parent_category = category.filter(parent=None).count()
        # child_category = category.count() - parent_category
        # context = {
        #     'today_want_ad': today_want_ad.count(),
        #     'month_want_ad': month_want_ad,
        #     'year_want_ad': year_want_ad,
        #     'special': special_want,
        #     'top_city': top_city,
        #     'top_zone': top_zone,
        #     'paid': paid,
        #     'not_confirmed': not_confirmed,
        #     'category_count': category.count(),
        #     'parent_category': parent_category,
        #     'child_category': child_category,
        #     'top_date': top_date,
        # }
        return render(request, "config/static.html")


class LandingView(TemplateView):
    template_name = "config/landing.html"

config/templates/config/about_create.html
{% extends 'base.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-success text-center">درباره برنامه</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {{ form.media }}
                                        {% csrf_token %}
                                            <div class="form-group">
                                            <label for="exampleInputEmail1">{{ form.title.label }}</label>
                                            {{ form.title }}
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">{{ form.description.label }}</label>
                                            {{ form.description }}
                                        </div>
                                        <button type="submit" class="btn btn-primary">ثبت</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->

config/templates/config/about_us.html
{% extends "base.html" %}

{% block content %}
<main class="main-content">

    <div class="container">

        <!-- begin::page-header -->
        <div class="page-header">
            <h1 class="text-center"> درباره ما</h1>
            <nav aria-label="breadcrumb">
                <ol><a class="btn btn-danger" href="{% url "config:about_create" %}">تغییر متن درباره ما</a></ol>
            </nav>
        </div>
        <!-- end::page-header -->


        <div class="row">
            <div class="col-md-12">
                <h5></h5>
                <hr>
                <div class="col-md-12">
                    <div class="card bg-primary col-md-12 text-center text-center">
                        <blockquote class="blockquote mb-0 card-body">
                            {% if about_us.description %}
                                <h1>{{ about_us.description | safe | linebreaks }}</h1>
                            {% else %}
                                <h1>شما متنی برای بخش درباره ما در نظز نگرفتید</h1>
                            {% endif %}
                        </blockquote>
                    </div>

                </div>
            </div>
        </div>

    </div>

</main>
<!-- end::main content -->
{% endblock content %}

config/templates/config/contact_list.html
{% extends "base.html" %}
{% block content %}
    <main class="main-content">
        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">لیست پیام های دریافتی</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">


                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">پیام های دریافتی</h6>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">ایمیل</th>
                                        <th scope="col">عنوان</th>
                                        <th scope="col">تاریخ</th>
                                        <th scope="col">جزییات</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for  contact  in  contact_list %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ contact.email }}</td>
                                            <td>{{ contact.title }}</td>
                                            <td>{{ contact.created }}</td>
                                            <td><a href="{% url "config:contact_detail" contact.pk %}">جزییات</a></td>
                                        </tr>
                                    {% empty %}
                                        <h1 class="text-center text-danger">پیامی دربافت نشده</h1>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </main>
{% endblock content %}

config/templates/config/cost.html
{% extends "base1.html" %}
{% load humanize %}
{% block content %}
    <main class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center"> نرخ های آگهی</h1>
                <nav aria-label="breadcrumb">
                    <ol><a class="btn btn-danger" href="{% url "config:cost_set" %}">تعییر نرخ آگهی</a></ol>
                </nav>
            </div>
            <!-- end::page-header -->


            <div class="row">
                <div class="col-md-12">
                    <h5></h5>
                    <hr>
                    <div class="card-columns">
                        <div class="card bg-primary text-center p-3">
                            <blockquote class="blockquote mb-0 card-body">
                                <h1> در شهرهای بزرگ</h1>
                                {{ info.capital | intcomma }}
                                تومان

                            </blockquote>
                        </div>
                        <div class="card bg-primary text-center p-3">
                            <blockquote class="blockquote mb-0 card-body">
                                <h1> در سایز شهرها</h1>
                                {{ info.others | intcomma }}
                                تومان
                            </blockquote>
                        </div>
                        <div class="card bg-primary text-center p-3">
                            <blockquote class="blockquote mb-0 card-body">
                                <h1> ویژه</h1>
                                {{ info.special | intcomma }}
                                تومان

                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </main>
    <!-- end::main content -->
{% endblock content %}

config/templates/config/cost_set.html
{% extends 'base1.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-success text-center">اعمال نرخه آگهی</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        {% for field in form.visible_fields %}
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        {% endfor %}
                                        <button type="submit" class="btn btn-primary">ثبت</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->

config/templates/config/rule.html
{% extends "base.html" %}

{% block content %}
<main class="main-content">

    <div class="container">

        <!-- begin::page-header -->
        <div class="page-header">
            <h1 class="text-center"> قوانین برنامه</h1>
            <nav aria-label="breadcrumb">
                <ol><a class="btn btn-danger" href="{% url "config:rule_create" %}">تغییر متن قوانین</a></ol>
            </nav>
        </div>
        <!-- end::page-header -->


        <div class="row">
            <div class="col-md-12">
                <h5></h5>
                <hr>
                <div class="col-md-12">
                    <div class="card bg-primary text-center">
                        <blockquote class="blockquote mb-0 card-body">
                            {% if about_us.description %}
                                <h1>{{ about_us.description | safe | linebreaks }}</h1>
                            {% else %}
                                <h1>شما متنی برای بخش درباره ما در نظز نگرفتید</h1>
                            {% endif %}
                        </blockquote>
                    </div>

                </div>
            </div>
        </div>

    </div>

</main>
<!-- end::main content -->
{% endblock content %}

config/templates/config/rule_create.html
{% extends 'base.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-success text-center">قوانین برنامه</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        {{ form.media }}
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">{{ form.title.label }}</label>
                                            {{ form.title }}
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">{{ form.description.label }}</label>
                                            {{ form.description }}
                                        </div>

                                        <button type="submit" class="btn btn-primary">ثبت</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->