accounts/urls.py
from django.urls import include, path

from accounts.api.urls import urlpatterns

from .views import (AddNewAdminView, AdminListView, AdminLoginView, LogoutView,
                    UserDeleteView, UserDetailView, UserListView)

app_name = "accounts"

urlpatterns = [
    path("login/", AdminLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("admin_list/", AdminListView.as_view(), name="admin_list"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("admin_create/", AddNewAdminView.as_view(), name="admin_create"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="delete"),
    path("user_detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("api/", include(urlpatterns)),
]

chat/urls.py
from django.urls import include, path

from chat.api.urls import urlpatterns

app_name = "chat"
urlpatterns = [
    path("api/", include(urlpatterns)),
]

config/urls.py
from django.urls import include, path

from config.api.urls import urlpatterns

from .views import (ContactDetailView,
                    ContactListView, PanelView, LandingView)

from .views import (AboutUsCreateView, AboutUsView, ContactDetailView,
                PanelView, RuleCreateView, RuleView, LandingView)


app_name = "config"

urlpatterns = [
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("about_create/", AboutUsCreateView.as_view(), name="about_create"),
    path("rule_create/", RuleCreateView.as_view(), name="rule_create"),
    path("rule/", RuleView.as_view(), name="rule"),
    path("contact_list/", ContactListView.as_view(), name="contact_list"),
    path(
        "contact_detail/<int:pk>/", ContactDetailView.as_view(), name="contact_detail"
    ),
    path("api/", include(urlpatterns)),
    path("panel/", PanelView.as_view(), name="panel"),
    path("", LandingView.as_view(), name="landing"),
]

financial/urls.py
from django.urls import include, path

from financial.api.urls import urlpatterns

from .views import (CartPayAcceptedListView, CartPayNotConfirmedListView,
                    OriginCartCreateView, OriginCartListView, OriginDeleteView,
                    OriginUpdateView, PayHistoryListView, TariffCreateView,
                    TariffDeleteView, TariffListView, TariffUpdateView)

app_name = "financial"
urlpatterns = [
    path("tarrif_list/", TariffListView.as_view(), name="tariff_list"),
    path("tarrif_create/", TariffCreateView.as_view(), name="tariff_create"),
    path("tarrif_update/<int:pk>/", TariffUpdateView.as_view(), name="tariff_update"),
    path("tarrif_delete/<int:pk>/", TariffDeleteView.as_view(), name="tariff_delete"),
    path("origin_list/", OriginCartListView.as_view(), name="origin_list"),
    path("origin_create/", OriginCartCreateView.as_view(), name="origin_create"),
    path("origin_update/<int:pk>/", OriginUpdateView.as_view(), name="origin_update"),
    path("origin_delete/<int:pk>/", OriginDeleteView.as_view(), name="origin_delete"),
    path("pay_list/", PayHistoryListView.as_view(), name="pay_history"),
    path("cart_pay/", CartPayAcceptedListView.as_view(), name="cart_pay"),
    path("cart_pay_wait/", CartPayNotConfirmedListView.as_view(), name="cart_pay_wait"),
    path("api/", include(urlpatterns)),
]

lovinoo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("config.urls", namespace="config")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("activity/", include("activity.urls", namespace="activity")),
    path("financial/", include("financial.urls", namespace="financial")),
]
if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>قالب Protable - قالب پنل مدیریت</title>


    <!-- Css -->

    <!-- Javascript -->

    <!-- Favicon -->
        <!-- Favicon -->

    <!-- Plugin styles -->


    <!-- Prism -->
    <link rel="stylesheet" href="{%  static 'vendors/prism/prism.css' %}" type="text/css">

    <!-- App styles -->

    <link rel="shortcut icon" href="{% static 'media/image/favicon.png' %}">

    <!-- Plugin styles -->
    <link rel="stylesheet" href="{% static 'vendors/bundle.css' %}" type="text/css">

    <!-- Datepicker -->
    <link rel="stylesheet" href="{% static 'datepicker/daterangepicker.css' %}">

    <!-- Slick -->
    <link rel="stylesheet" href="{% static 'vendors/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/slick/slick-theme.css' %}">

    <!-- Vmap -->
    <link rel="stylesheet" href="{% static 'vendors/vmap/jqvmap.min.css' %}">

    <!-- App styles -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css">
    {% block style %}
    {% endblock style %}
</head>
<body>
<!-- begin::preloader-->

{#<div class="preloader">#}
{#    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="50px" height="50px" viewbox="0 0 128 128" xml:space="preserve">#}
{#        <rect x="0" y="0" width="100%" height="100%" fill="#FFFFFF" />#}
{#        <g>#}
{#            <path d="M75.4 126.63a11.43 11.43 0 0 1-2.1-22.65 40.9 40.9 0 0 0 30.5-30.6 11.4 11.4 0 1 1 22.27 4.87h.02a63.77 63.77 0 0 1-47.8 48.05v-.02a11.38 11.38 0 0 1-2.93.37z" fill="#000000" fill-opacity="1" />#}
{#        </g>#}
{#    </svg>#}
{#</div>#}

{% include 'navbar.html' %}
<div id="main">

    {% include 'header.html' %}
    {% if messages %}
        {% for message in messages %}
            <p class="alert alert-{{ message.tags }}">{{ message }}</p>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
    <!-- begin::footer -->
    <footer>
        <div class="container">
            <div>ارائه شده در وب‌سایت <a href="https://www.rtl-theme.com" target="_blank">راست‌چین</a></div>
            <div>
                <nav class="nav">
                    <a href="#" class="nav-link">مجوزها</a>
                    <a href="#" class="nav-link">تغییرات</a>
                    <a href="#" class="nav-link">راهنما</a>
                </nav>
            </div>
        </div>
    </footer>
    <!-- end::footer -->

</div>

<!-- Plugin scripts -->
<script src="{% static 'vendors/bundle.js' %}"></script>

<!-- Chartjs -->
<script src="{% static 'vendors/charts/chartjs/chart.min.js' %}"></script>

<!-- Apex chart -->
<script src="{% static 'vendors/charts/apex/apexcharts.min.js' %}"></script>

<!-- Circle progress -->
<script src="{% static 'vendors/circle-progress/circle-progress.min.js' %}"></script>

<!-- Peity -->
<script src="{% static 'vendors/charts/peity/jquery.peity.min.js' %}"></script>
<script src="{% static 'js/examples/charts/peity.js' %}"></script>

<!-- Datepicker -->
<script src="{% static 'vendors/datepicker/daterangepicker.js' %}"></script>

<!-- Slick -->
<script src="{% static 'vendors/slick/slick.min' %}.js"></script>

<!-- Vamp -->
<script src="{% static 'vendors/vmap/jquery.vmap' %}.min.js"></script>
<script src="{% static 'vendors/vmap/maps/jquery' %}.vmap.usa.js"></script>
<script src="{% static 'js/examples/vmap' %}.js"></script>

<!-- Dashboard scripts -->
<script src="{% static 'js/examples/dashboard.js' %}"></script>
<div class="colors"> <!-- To use theme colors with Javascript -->
    <div class="bg-primary"></div>
    <div class="bg-primary-bright"></div>
    <div class="bg-secondary"></div>
    <div class="bg-secondary-bright"></div>
    <div class="bg-info"></div>
    <div class="bg-info-bright"></div>
    <div class="bg-success"></div>
    <div class="bg-success-bright"></div>
    <div class="bg-danger"></div>
    <div class="bg-danger-bright"></div>
    <div class="bg-warning"></div>
    <div class="bg-warning-bright"></div>
</div>

<!-- App scripts -->
<script src="{% static 'js/app.js' %}"></script>

</body>
</html>

templates/header.html
{% load static %}
<div class="header">

    <!-- begin::header left -->
    <ul class="navbar-nav">

        <!-- begin::navigation-toggler -->
        <li class="nav-item navigation-toggler">
            <a href="#" class="nav-link">
                <i data-feather="menu"></i>
            </a>
        </li>
        <!-- end::navigation-toggler -->

        <!-- begin::header-logo -->
        <li class="nav-item" id="header-logo">
            <a href="index.html">
                <img class="logo" src="{% static 'media/image/logo.png'  %}"  alt="logo">
                <img class="logo-sm" src="{% static 'media/image/logo-sm.png' %}" alt="small logo">
                <img class="logo-dark" src="{% static 'media/image/logo-dark.png' %}" alt="dark logo">
            </a>
        </li>
        <!-- end::header-logo -->
    </ul>
    <!-- end::header left -->

    <!-- begin::header-right -->
    <div class="header-right">
        <ul class="navbar-nav">

{#            <!-- begin::search-form -->#}
            {#            <li class="nav-item search-form">#}
            {#                <div class="row">#}
            {#                    <div class="col-md-6">#}
            {#                        <form>#}
            {#                            <div class="input-group">#}
            {#                                <input type="text" class="form-control" placeholder="جستجو">#}
            {#                                <div class="input-group-append">#}
            {#                                    <button class="btn btn-default" type="button">#}
            {#                                        <i data-feather="search"></i>#}
            {#                                    </button>#}
            {#                                </div>#}
            {#                            </div>#}
            {#                        </form>#}
            {#                    </div>#}
            {#                </div>#}
            {#            </li>#}
            {#            <!-- end::search-form -->#}

            <!-- begin::header minimize/maximize -->
            <li class="nav-item dropdown">
                <a href="#" class="nav-link" title="Fullscreen" data-toggle="fullscreen">
                    <i class="maximize" data-feather="maximize"></i>
                    <i class="minimize" data-feather="minimize"></i>
                </a>
            </li>
            <!-- end::header minimize/maximize -->

        </ul>

        <!-- begin::mobile header toggler -->
        <ul class="navbar-nav d-flex align-items-center">
            <li class="nav-item header-toggler">
                <a href="#" class="nav-link">
                    <i data-feather="arrow-down"></i>
                </a>
            </li>
        </ul>
        <!-- end::mobile header toggler -->
    </div>
    <!-- end::header-right -->
</div>

templates/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Echo Text</title>
</head>
<body>
    <textarea id="echo-log" cols="100" rows="20"></textarea><br/>
    <input id="text-input" type="text" size="100"/><br/>
    <input id="text-submit" type="button" value="Enter"/>

    <script>
        var socket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/?name=test&version=');

        socket.onmessage = function(e) {
            var message = e.data;
            document.querySelector('#echo-log').value += (message + '\n');
        };

        socket.onclose = function(e) {
            console.error('Socket closed unexpectedly');
        };

        document.querySelector('#text-input').focus();
        document.querySelector('#text-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#text-submit').click();
            }
        };

        document.querySelector('#text-submit').onclick = function(e) {
            var messageInputDom = document.querySelector('#text-input');
            var message = messageInputDom.value;
            socket.send(message);

            messageInputDom.value = '';
        };
    </script>
</body>
</html>

templates/navbar.html
{% with request.resolver_match.url_name as url_name %}


    <div class="navigation">

        <!-- begin::logo -->
        <div id="logo">
            <a href="index.html">
                <img class="logo" src="assets/media/image/logo.png" alt="logo">
                <img class="logo-sm" src="assets/media/image/logo-sm.png" alt="small logo">
                <img class="logo-dark" src="assets/media/image/logo-dark.png" alt="dark logo">
            </a>
        </div>
        <!-- end::logo -->

        <!-- begin::navigation header -->
        <header class="navigation-header">
            <figure class="avatar avatar-state-success">
                <img src="assets/media/image/user/man_avatar3.jpg" class="rounded-circle" alt="image">
            </figure>
            <div>
                <h5>{{ request.user }}</h5>
                <p class="text-muted line-height-20 m-b-25">مدیر</p>
                <ul class="nav">
                    <li class="nav-item">
                        <a href="profile.html" class="btn nav-link bg-info-bright" title="پروفایل"
                           data-toggle="tooltip">
                            <i data-feather="user"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="btn nav-link bg-success-bright" title="تنظیمات" data-toggle="tooltip">
                            <i data-feather="settings"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url "accounts:logout" %}" class="btn nav-link bg-danger-bright" title="خروج"
                           data-toggle="tooltip">
                            <i data-feather="log-out"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </header>
        <!-- end::navigation header -->

        <!-- begin::navigation menu -->
        <div class="navigation-menu-body">
            <ul>
                <li class="navigation-divider">اصلی</li>

                <li>
                    <a class="{% if url_name == 'panel' %}active{% endif %}" href="{% url "config:panel" %}">
                        <i class="nav-link-icon" data-feather="bar-chart-2"></i>
                        <span>داشبورد</span>
                        <span class="badge badge-danger">2</span>
                    </a>
                </li>

                <li class="{% if request.resolver_match.app_name == 'accounts' %}open{% endif %}">
                    <a href="">
                        <i class="nav-link-icon" data-feather="bar-chart-2"></i>
                        <span>کاربران برنامه</span>
                    </a>
                    <ul>
                        <li><a class="{% if url_name == 'user_list' %}active{% endif %}"
                               href="{% url "accounts:user_list" %}">لیست </a></li>

                    </ul>
                </li>
                <li class="{% if request.resolver_match.app_name == 'accounts' %}open{% endif %}">
                    <a href="">
                        <i class="nav-link-icon" data-feather="bar-chart-2"></i>
                        <span>کاربران ادمین</span>
                    </a>
                    <ul>
                        <li><a class="{% if url_name == 'admin_list' %}active{% endif %}"
                               href="{% url "accounts:admin_list" %}">لیست </a></li>
                        <li><a class="{% if url_name == 'admin_create' %}active{% endif %}"
                               href="{% url "accounts:admin_create" %}">افزودن</a></li>
                    </ul>
                </li>

                <li class="{% if request.resolver_match.app_name == 'financial' %}open{% endif %}">
                    <a href="">
                        <i class="nav-link-icon" data-feather="bar-chart-2"></i>
                        <span>مالی</span>
                    </a>
                    <ul>
                        <li><a class="{% if url_name == 'tariff_list' %}active{% endif %}"
                               href="{% url "financial:tariff_list" %}">تعرفه ها</a></li>
                        <li><a class="{% if url_name == 'origin_list' %}active{% endif %}"
                               href="{% url "financial:origin_list" %}">شماره کارت ها</a></li>
                        <li><a class="{% if url_name == 'pay_history' %}active{% endif %}"
                               href="{% url "financial:pay_history" %}">پرداخنی ها</a></li>
                        <li><a class="{% if url_name == 'cart_pay' %}active{% endif %}"
                               href="{% url "financial:cart_pay" %}">کارت به کارت ها</a></li>
                    </ul>
                </li>
                <li>
                    <a class="{% if url_name == 'contact_list' %}active{% endif %}" href="{% url "config:contact_list" %}">
                        <i class="nav-link-icon" data-feather="check-circle"></i>
                        <span>Contact</span>
                        <span class="badge badge-warning">2</span>
                    </a>
                </li>
                <li class="{% if request.resolver_match.app_name == 'config' %}open{% endif %}">
                    <a href="">
                        <i class="nav-link-icon" data-feather="bar-chart-2"></i>
                        <span>تنظیمات</span>
                    </a>
                    <ul>
<!--                         <li><a class="{% if url_name == 'rule' %}active{% endif %}" -->
<!--                                href="{% url "config:rule" %}">قوانین</a></li> -->
                        <li><a class="{% if url_name == 'about_us' %}active{% endif %}"
                               href="{% url "config:about_us" %}">درباره ما</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- end::navigation menu -->

    </div>
{% endwith %}