chat/urls.py
from django.urls import include, path

from chat.api.urls import urlpatterns

app_name = "chat"
urlpatterns = [
    path("api/", include(urlpatterns)),
]

financial/api/urls.py
from django.urls import path

from .views import (CartPayCreateApiView, TariffListApiView,
                    UserCartPayApiView, UserHistoryPay, CartPayView, VerifyPayView, Paymentno, Paymentok)

urlpatterns = [
    path("", TariffListApiView.as_view()),
    path("cart_pay/", CartPayCreateApiView.as_view()),
    path("user_cart_pay/", UserCartPayApiView.as_view()),
    path("user_pay/", UserHistoryPay.as_view()),
    path("user_pay/", UserHistoryPay.as_view()),
    path('pay/<int:pk>/', CartPayView.as_view()),
    path('verify/', VerifyPayView.as_view()),
    path('paymentok/', Paymentok.as_view()),
    path('paymentno/', Paymentno.as_view()),
]

financial/urls.py
from django.urls import include, path

from financial.api.urls import urlpatterns

from .views import (CartPayAcceptedListView, CartPayNotConfirmedListView,
                    OriginCartCreateView, OriginCartListView, OriginDeleteView,
                    OriginUpdateView, PayHistoryListView, TariffCreateView,
                    TariffDeleteView, TariffListView, TariffUpdateView)

app_name = "financial"
urlpatterns = [
    path("tarrif_list/", TariffListView.as_view(), name="tariff_list"),
    path("tarrif_create/", TariffCreateView.as_view(), name="tariff_create"),
    path("tarrif_update/<int:pk>/", TariffUpdateView.as_view(), name="tariff_update"),
    path("tarrif_delete/<int:pk>/", TariffDeleteView.as_view(), name="tariff_delete"),
    path("origin_list/", OriginCartListView.as_view(), name="origin_list"),
    path("origin_create/", OriginCartCreateView.as_view(), name="origin_create"),
    path("origin_update/<int:pk>/", OriginUpdateView.as_view(), name="origin_update"),
    path("origin_delete/<int:pk>/", OriginDeleteView.as_view(), name="origin_delete"),
    path("pay_list/", PayHistoryListView.as_view(), name="pay_history"),
    path("cart_pay/", CartPayAcceptedListView.as_view(), name="cart_pay"),
    path("cart_pay_wait/", CartPayNotConfirmedListView.as_view(), name="cart_pay_wait"),
    path("api/", include(urlpatterns)),
]

lovinoo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("config.urls", namespace="config")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("activity/", include("activity.urls", namespace="activity")),
    path("financial/", include("financial.urls", namespace="financial")),
]
if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

    

financial/models.py
from django.conf import settings
from django.db import models
from django_extensions.db.models import TimeStampedModel

user = settings.AUTH_USER_MODEL


# Create your models here.
class Tariff(models.Model):
    title = models.CharField(max_length=255)
    price = models.IntegerField()
    time = models.IntegerField()

    def __str__(self):
        return f"{self.title}-{self.price}"


class OriginCart(models.Model):
    number = models.CharField(max_length=16)


class CartPay(TimeStampedModel):
    class STATUS(models.TextChoices):
        waiting = "waiting", " در انتظار تایید"
        accepted = "accepted", "تایید شده"
        rejected = "rejected", " تایید نشد"

    user = models.ForeignKey(
        user, on_delete=models.CASCADE, related_name="cart_pays", null=True, blank=True
    )
    name = models.CharField(max_length=255)
    time = models.DateTimeField()
    tracing_number = models.CharField(max_length=20)
    image = models.ImageField(upload_to="cart_pay/")
    description = models.TextField(blank=True)
    cart_number = models.CharField(max_length=16)
    origin_cart = models.ForeignKey(OriginCart, on_delete=models.PROTECT)
    tariff = models.ForeignKey(Tariff, on_delete=models.PROTECT)
    status = models.CharField(max_length=15, choices=STATUS.choices, default="waiting")


class PayHistory(models.Model):
    user = models.ForeignKey(
        user,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="pays",
    )
    price = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True)
    tariff = models.CharField(max_length=125)
    authority = models.CharField(null=True, blank=True, max_length=100)

financial/forms.py
from django import forms

from .models import OriginCart, Tariff


class TariffForm(forms.ModelForm):
    class Meta:
        model = Tariff
        fields = (
            "title",
            "price",
            "time",
        )
        labels = {
            "title": "عنوان اشتراک",
            "price": "قیمت اشتراک ",
            "time": "مدت اشتراک",
        }
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "price": forms.NumberInput(attrs={"class": "form-control"}),
            "time": forms.NumberInput(attrs={"class": "form-control"}),
        }


class OriginCartForm(forms.ModelForm):
    class Meta:
        model = OriginCart
        fields = ("number",)
        labels = {
            "number": "شماره کارت",
        }
        widgets = {
            "number": forms.TextInput(attrs={"class": "form-control"}),
        }

financial/api/views.py
import json
import requests
from lovinoo.celery import app
from django.http import HttpResponse
from django.shortcuts import redirect , render
from rest_framework import status
from rest_framework.generics import CreateAPIView, ListAPIView, GenericAPIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from django.views.generic import View
from ..models import CartPay, Tariff, PayHistory
from .serializers import (CartPaySerializer, PayHistorySerializers,
                          TariffSerializer)
from celery import shared_task


@shared_task
def connect_gateway(price, phone):
    req_data = {
        "merchant_id": MERCHANT,
        "amount": price,
        "callback_url": CallbackURL,
        "description": description,
        "metadata": {"mobile": phone}
    }
    req_header = {"accept": "application/json",
                  "content-type": "application/json'"}
    req = requests.post(url=ZP_API_REQUEST, data=json.dumps(
        req_data), headers=req_header)
    return req


class TariffListApiView(ListAPIView):
    serializer_class = TariffSerializer
    queryset = Tariff.objects.all()

    def list(self, request, *args, **kwargs):
        response = super().list(request, *args, **kwargs)
        return Response(
            {"is_done": True, "message": "لیست تغرفه ها", "data": response.data}
        )


class CartPayCreateApiView(CreateAPIView):
    serializer_class = CartPaySerializer
    queryset = CartPay.objects.all()

    def perform_create(self, serializer):
        serializer.save(user_id=self.request.user.id)

    def create(self, request, *args, **kwargs):
        response = super().create(request, *args, **kwargs)
        return Response({"is_done": True, "data": response.data})


class UserCartPayApiView(ListAPIView):
    serializer_class = CartPaySerializer

    def get_queryset(self):
        cart_pays = self.request.user.cart_pays.all()
        return cart_pays

    def list(self, request, *args, **kwargs):
        response = super(UserCartPayApiView, self).list(
            request, *args, **kwargs)
        return Response({"is_done": True, "data": response.data})


class UserHistoryPay(ListAPIView):
    serializer_class = PayHistorySerializers

    def get_queryset(self):
        cart_pays = self.request.user.pays.all()
        return cart_pays

    def list(self, request, *args, **kwargs):
        response = super(UserHistoryPay, self).list(request, *args, **kwargs)
        return Response({"is_done": True, "data": response.data})


MERCHANT = '0af09ec7-5cfe-4d7c-9356-f23447eb680b'
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"
CallbackURL = 'https://lovino.darkube.app/financial/api/verify/'


class CartPayView(GenericAPIView):
    permission_classes = [IsAuthenticated, ]

    def get(self, request, *args, **kwargs):
        tariff_obj = Tariff.objects.get(id=kwargs.get('pk'))
        # req = connect_gateway.delay(tariff_obj.price, request.user.phone_number)
        req = connect_gateway(tariff_obj.price, request.user.phone_number)
        authority = req.json()['data']['authority']
        PayHistory.objects.create(user=self.request.user, price=tariff_obj.price, tariff=tariff_obj.title,
                                  authority=authority)
        context = {
            'is_done': True,
            'message': "در حال انتقال به درگاه پرداخت",
            'data': ZP_API_STARTPAY.format(authority=authority)
        }
        return Response(data=context, status=status.HTTP_200_OK)


class VerifyPayView(GenericAPIView):
    permission_classes = [AllowAny, ]
    def get(self, request):
        t_status = request.GET.get('Status')
        t_authority = request.GET['Authority']
        pay_history_obj = PayHistory.objects.get(authority=t_authority)
        if request.GET.get('Status') == 'OK':
            req_header = {"accept": "application/json",
                          "content-type": "application/json'"}
            req_data = {
                "merchant_id": MERCHANT,
                "amount": pay_history_obj.price,
                "authority": t_authority
            }
            req = requests.post(url=ZP_API_VERIFY, data=json.dumps(
                req_data), headers=req_header)
            if len(req.json()['errors']) == 0:
                t_status = req.json()['data']['code']
                if t_status == 100:
                    return redirect('/financial/api/paymentok/')
                elif t_status == 101:
                    return redirect('/financial/api/paymentno/')
                else:
                    PayHistory.objects.get(authority=t_authority).delete()
                    return redirect('/financial/api/paymentok/')
            else:
                PayHistory.objects.get(authority=t_authority).delete()
                return redirect('/financial/api/paymentok/')
        else:
            PayHistory.objects.get(authority=t_authority).delete()
            return redirect('/financial/api/paymentok/')


class Paymentok(View):
    def get(self, request, *args, **kwargs):
        return render(request,'../templates/financial/paymentok.html')

class Paymentno(View):
    def get(self, request, *args, **kwargs):
        return render(request,'../templates/financial/paymentno.html')

financial/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, View

from .forms import OriginCartForm, TariffForm
from .models import CartPay, OriginCart, PayHistory, Tariff

# Create your views here.


class TariffCreateView(SuccessMessageMixin, CreateView):
    model = Tariff
    form_class = TariffForm
    success_url = reverse_lazy("financial:tariff_list")
    success_message = ""
    template_name = "financial/tariff_create.html"

    def form_invalid(self, form):
        messages.error(self.request, "", "")
        return super(TariffCreateView, self).form_invalid(form)


class TariffListView(ListView):
    model = Tariff
    template_name = "financial/tariff_list.html"


class TariffUpdateView(SuccessMessageMixin, UpdateView):
    model = Tariff
    form_class = TariffForm
    success_url = reverse_lazy("financial:tariff_list")
    success_message = "پلن با موفقیت به روززسانی شد"
    template_name = "financial/tariff_update.html"

    def form_invalid(self, form):
        messages.error(self.request, "حطا", "danger")
        return super(TariffUpdateView, self).form_invalid(form)


class TariffDeleteView(View):
    def get(self, request, pk):
        tariff = get_object_or_404(Tariff, pk=pk)
        tariff.delete()
        messages.success(request, "پلن با موفقیت حذف شد", "success")
        return redirect("financial:tariff_list")


class OriginCartListView(ListView):
    model = OriginCart
    template_name = "financial/origin_list.html"


class OriginCartCreateView(SuccessMessageMixin, CreateView):
    model = OriginCart
    form_class = OriginCartForm
    success_url = reverse_lazy("financial:origin_list")
    success_message = ""
    template_name = "financial/origin_create.html"

    def form_invalid(self, form):
        messages.error(self.request, "", "")
        return super(OriginCartCreateView, self).form_invalid(form)


class OriginUpdateView(SuccessMessageMixin, UpdateView):
    model = OriginCart
    form_class = OriginCartForm
    success_url = reverse_lazy("financial:origin_list")
    success_message = "پلن با موفقیت به روززسانی شد"
    template_name = "financial/tariff_update.html"

    def form_invalid(self, form):
        messages.error(self.request, "حطا", "danger")
        return super(OriginUpdateView, self).form_invalid(form)


class OriginDeleteView(View):
    def get(self, request, pk):
        origin_cart = get_object_or_404(OriginCart, pk=pk)
        origin_cart.delete()
        messages.success(request, "پلن با موفقیت حذف شد", "success")
        return redirect("financial:origin_list")


class CartPayAcceptedListView(ListView):
    queryset = CartPay.objects.filter(status="accepted")
    template_name = "financial/cartpay_list.html"


class CartPayNotConfirmedListView(ListView):
    queryset = CartPay.objects.filter(status="waiting")
    template_name = "financial/cart_pay_wait.html"


class PayHistoryListView(ListView):
    model = PayHistory
    template_name = "financial/pay_list.html"

financial/templates/financial/cart_pay_wait.html
{% extends "base.html" %}
{% block content %}
    <main class="main-content">
        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">لیست پرداختی های کارت به کارت در انتظار تایید </h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">


                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title"></h6>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">کاربر</th>
                                        <th scope="col">نام</th>
                                        <th scope="col">شماره تراکنش</th>
                                        <th scope="col">تصویر</th>
                                        <th scope="col">جزییات</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for pay  in  object_list %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ pay.user }}</td>
                                            <td>{{ pay.name }}</td>
                                            <td>{{ pay.tracing_number }}</td>
                                            <td><a href="{{ pay.image.url }}"><img src="{{ pay.image.url }}"></a></td>
                                            <td><a href="{% url "financial:pay_history" %}" class="btn btn-info">نمایش
                                                جزییات</a></td>
                                        </tr>
                                    {% empty %}
                                        <h1 class="text-center text-danger">کارت به کارتی ثبت نشده</h1>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </main>
{% endblock content %}

financial/templates/financial/cartpay_list.html
{% extends "base.html" %}
{% block content %}
    <main class="main-content">
        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">لیست پرداختی های کارت به کارت</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">


                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title"><a href="{% url "financial:cart_pay_wait" %}" class="btn btn-apple">نمایش پرداخت های تایید نشده</a></h6>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">کاربر</th>
                                        <th scope="col">نام</th>
                                        <th scope="col">شماره تراکنش</th>
                                        <th scope="col">تصویر</th>
                                        <th scope="col">جزییات</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for pay  in  object_list %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ pay.user }}</td>
                                            <td>{{ pay.name }}</td>
                                            <td>{{ pay.tracing_number }}</td>
                                            <td><a href="{{ pay.image.url }}"><img src="{{ pay.image.url }}"></a></td>
                                            <td><a href="{% url "financial:pay_history" %}" class="btn btn-info">نمایش
                                                جزییات</a></td>
                                        </tr>
                                    {% empty %}
                                        <h1 class="text-center text-danger">کارت به کارتی ثبت نشده</h1>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </main>
{% endblock content %}

financial/templates/financial/notconfied_cartpay_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

financial/templates/financial/origin_create.html
{% extends 'base.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-success text-center">افزودن پلن اشتراکی</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        {% for field in form.visible_fields %}
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        {% endfor %}
                                        <button type="submit" class="btn btn-primary">ثبت</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->

financial/templates/financial/origin_list.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
    <main class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">شماره کارت ها برای کارت به کارت</h1>
                <nav aria-label="breadcrumb">
                    <ol><a class="btn btn-danger" href="{% url "financial:origin_create" %}">افزودن شماره گارت</a></ol>
                </nav>
            </div>
            <!-- end::page-header -->


            <div class="row">
                <div class="col-md-12">
                    <h5></h5>
                    <hr>
                    <div class="col-md-12">
                        {% for origin in origincart_list %}
                            <div class="card   border border-success  text-center ">
                                <blockquote class="col-md-9 m-auto">
                                    <h1>{{ origin.number }}</h1>
                                    <a href="{% url "financial:origin_delete" origin.pk %}" class="btn btn-danger">حذف
                                        شماره کارت</a>
                                    <a href="{% url "financial:origin_update" origin.pk %}" class="btn btn-warning">به
                                        روززسانی شماره کارت</a>
                                </blockquote>
                            </div>
                        {% empty %}
                            <h1 class="text-center text-danger"> شماره کارتی برای برنامه درنظر نگرفته اید</h1>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>

    </main>
    <!-- end::main content -->
{% endblock content %}

financial/templates/financial/origin_update.html
{% extends 'base.html' %}
<!-- end::header -->
{% block content %}
    <!-- begin::main-content -->
    <div class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-warning text-center">به روزرسانی پلن {{ object }}</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        {% for field in form.visible_fields %}
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        {% endfor %}
                                        <button type="submit" class="btn btn-warning">ثبت تغییرات</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>

    </div>
    <!-- end::main-content -->
{% endblock content %}
<!-- begin::footer -->

financial/templates/financial/pay_list.html
{% extends "base.html" %}
{% block content %}
    <main class="main-content">
        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">لیست پرداختی های کاربران</h1>
            </div>
            <!-- end::page-header -->

            <div class="row">
                <div class="col-md-12">


                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">کاربران ادمین</h6>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">کاربر</th>
                                        <th scope="col">اشتراک</th>
                                        <th scope="col">مبلغ</th>
                                        <th scope="col">تاریخ</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for pay in payhistory_list %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ pay.user }}</td>
                                            <td>{{ pay.tariff }}</td>
                                            <td>{{ pay.price }}</td>
                                            <td>{{ pay.date }}</td>
                                        </tr>
                                    {% empty %}
                                        <h1 class="text-center text-danger">پرداختی در سیستم ثبت نشده</h1>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </main>
{% endblock content %}

financial/templates/financial/paymentno.html
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="utf-8">
</head>
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<style type="text/css">

    body
    {
        background:#f2f2f2;
    }

    .payment
	{
		border:1px solid #f2f2f2;
		height:280px;
        border-radius:20px;
        background:#fff;
	}
   .payment_header
   {
	   background:rgba(255,102,0,1);
	   padding:20px;
       border-radius:20px 20px 0px 0px;

   }

   .check
   {
	   margin:0px auto;
	   width:50px;
	   height:50px;
	   border-radius:100%;
	   background:#fff;
	   text-align:center;
   }

   .check i
   {
	   vertical-align:middle;
	   line-height:50px;
	   font-size:30px;
   }

    .content
    {
        text-align:center;
    }

    .content  h1
    {
        font-size:25px;
        padding-top:25px;
    }

    .content a
    {
        width:200px;
        height:35px;
        color:#fff;
        border-radius:30px;
        padding:5px 10px;
        background:rgba(255,102,0,1);
        transition:all ease-in-out 0.3s;
    }

    .content a:hover
    {
        text-decoration:none;
        background:#000;
    }

</style>
<body>
<div class="container">
   <div class="row">
      <div class="col-md-6 mx-auto mt-5">
         <div class="payment">
            <div class="payment_header">
               <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
            </div>
            <div class="content">
               <h1>پرداخت انجام نشد</h1>
               <p>پرداخت موفقیت آمیز نبود</p>
               <a href="app://lovinoo">بازگشت به برنامه</a>
            </div>
         </div>
      </div>
   </div>
</div>
=======
<a href="app://lovinoo">Google</a>
</body>
</html>

financial/templates/financial/tariff_list.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
    <main class="main-content">

        <div class="container">

            <!-- begin::page-header -->
            <div class="page-header">
                <h1 class="text-center">پلن های اشتراکی</h1>
                <nav aria-label="breadcrumb">
                    <ol><a class="btn btn-danger" href="{% url "financial:tariff_create" %}">افزودن پلن جدید</a></ol>
                </nav>
            </div>
            <!-- end::page-header -->


            <div class="row">
                <div class="col-md-12">
                    <h5></h5>
                    <hr>
                    <div class="card-columns">
                        {% for tariff in tariff_list %}
                            <div class="card  border border-success  text-center p-3">
                                <blockquote class="blockquote mb-0 card-body">
                                    <h1>{{ tariff.title }}</h1>
                                    <p>هزینه اشتراک:{{ tariff.price | intcomma }}
                                        تومان</p>
                                    <p>مدت زمان :{{ tariff.time }}
                                        ماه</p>
                                <a  href="{% url "financial:tariff_delete" tariff.pk %}" class="btn btn-danger">حذف پلن</a>
                                <a href="{% url "financial:tariff_update" tariff.pk %}" class="btn btn-warning">به روززسانی پلن</a>
                                </blockquote>
                            </div>
                        {% empty %}
                            <h1 class="text-center text-danger"> اشنراکی برای برنامه درنظر نگرفته اید</h1>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>

    </main>
    <!-- end::main content -->
{% endblock content %}